using System;
using System.Collections.Generic;

namespace Zoogle.Models
{
    public static class Zoo
    {
        public static readonly List<Animal> Animals = new List<Animal>
        {
            new Animal("Bush Cricket", "Tettigonia viridissima", "Tettigonia viridissima is distinguished by its very long and thin antennae, which can sometimes reach up to three times the length of the body, thus differentiating them from grasshoppers, which always carry short antennae.", new string[] { "Meadows", "Grasslands", "Prairies" }, "Swarm",  36, 0.001, "https://content.codecademy.com/courses/asp-dot-net/animal-icons/cricket.png"),
            new Animal("Common Box Turtle", "Terrapene carolina", "The box turtle has a distinctive hinged lowered shell (the box) that allows it to completely enclose itself. Its upper jaw is long and curved.", new string[] { "Woodlands", "Meadows", "Grasslands" }, "Bale", 127, 3.85, "https://content.codecademy.com/courses/asp-dot-net/animal-icons/turtle.png"),
            new Animal("Collared Dove", "Streptopelia decaocto", "The collared dove is not migratory, but is strongly dispersive. Over the last century, it has been one of the great colonisers of the bird world, travelling far beyond its native range to colonise colder countries, becoming a permanent resident in several.", new string[] { "Artic", "Mountainous", "Temperate Forest", "Subtropical" }, "Flight", 320, .24, "https://content.codecademy.com/courses/asp-dot-net/animal-icons/dove.png"),
            new Animal("Goat", "Capra aegagrus", "The wild goat (Capra aegagrus) is a wild goat species, inhabiting forests, shrublands and rocky areas ranging from Turkey and the Caucasus in the west to Turkmenistan, Afghanistan and Pakistan in the east. It has been listed as vulnerable on the IUCN Red List since 1996.", new string[] { "Forests", "Shrublands", "Mountainous" }, "Herd", 120, 50, "https://content.codecademy.com/courses/asp-dot-net/animal-icons/goat.png"),
            new Animal("Bengal Tiger", "Panthera tigris tigris", "The tiger is most recognisable for its dark vertical stripes on orangish-brown fur with a lighter underside. It is an apex predator, primarily preying on ungulates such as deer and wild boar. It is territorial and generally a solitary but social predator, requiring large contiguous areas of habitat, which support its requirements for prey and rearing of its offspring.", new string[] { "Tropical", "Grasslands" }, "Ambush", 270, 180, "https://content.codecademy.com/courses/asp-dot-net/animal-icons/tiger.png"),
            new Animal("Black Rat", "Rattus rattus", "The black rat is black to light brown in colour with a lighter underside. It is a generalist omnivore and a serious pest to farmers because it feeds on a wide range of agricultural crops. It is sometimes kept as a pet.", new string[] { "Urban", "Forests", "Mountainous" }, "Colony", 18, .20, "https://content.codecademy.com/courses/asp-dot-net/animal-icons/rat.png"),
            new Animal("Emerald Tree Boa", "Corallus caninus", "Corallus caninus, commonly called the emerald tree boa,[3] is a non-venomous boa species found in the rainforests of South America. The color pattern typically consists of an emerald green ground color with a white irregular interrupted zigzag stripe or so-called 'lightning bolts' down the back and a yellow belly.", new string[] { "Rainforest" }, "Nest", 1800, 27, "https://content.codecademy.com/courses/asp-dot-net/animal-icons/snake.png"),
            new Animal("Armhook Squid", "Berryteuthis magister", "The magister armhook squid, commander squid or schoolmaster gonate squid, is a medium-sized squid in the family Gonatidae. It is found in cold, high latitude waters of the North Pacific where it is among the most numerous squid species recorded.", new string[] { "High Latitude Waters" }, "Shoal", 55, .5, "https://content.codecademy.com/courses/asp-dot-net/animal-icons/squid.png"),
            new Animal("Unicorn", "Equus unicornus", "The unicorn is often depicted as a white horse-like or goat-like animal with a long horn and cloven hooves. In Middle Age encyclopedias, its horn was said to have the power to render poisoned water potable and to heal sickness.", new string[] { "Woodlands", "Narnia" }, "Herd", 140, 500, "https://content.codecademy.com/courses/asp-dot-net/animal-icons/unicorn.png" )
        };
    }
}
